In [4]:
import pandas as pd
import sqlite3

# Caminho do arquivo .db
db_path = 'database.db'

# Conectar ao banco de dados
conn = sqlite3.connect(db_path)

# Listar todas as tabelas disponíveis no banco de dados
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, conn)

print("Tabelas disponíveis no banco de dados:")
print(tables)

Tabelas disponíveis no banco de dados:
                 name
0            Aircraft
1     sqlite_sequence
2            Airfield
3          Airfield40
4             Country
5               Delay
6          DelayGroup
7         FlightStore
8              Limits
9        MobileDelete
10            myQuery
11            Setting
12         SyncDelete
13      SyncSignature
14     TypeOfApproach
15         Validation
16     ValidationTerm
17            Weather
18          WeatherAF
19  Raw_AirlineImport
20      AircraftCodes
21              Cloud
22          Allowance
23       myQueryBuild
24      AirfieldNotes
25      ExceptionLogs
26              Pilot
27             Flight

In [5]:
# Dicionário para armazenar os DataFrames
dataframes = {}

# Iterar sobre todas as tabelas e carregar seus dados
for table in tables['name']:
    dataframes[table] = pd.read_sql_query(f"SELECT * FROM {table};", conn)
    print(f"Dados da tabela '{table}':")
    print(dataframes[table].head())
    print("\n")

Dados da tabela 'Aircraft':
   AircraftCode  Active  DeviceCode     Make Model SubModel Rating Reference  \
0       1000006       1           1  Embraer  E190            E179    PR-AXE
1       1000007       1           1  Embraer  E190            E179    PR-AUJ
2       1000008       1           1  Embraer  E190            E179    PR-AXI
3       1000009       1           1  Embraer  E190            E179    PR-AYG
4       1000010       1           1  Embraer  E190            E179    PR-AUB

  RefSearch Fin  ...  DefaultApp  DefaultLaunch  DefaultLog  CondLog  Run2  \
0     PRAXE      ...           0              0           0       65     0
1     PRAUJ      ...           0              0           0       65     0
2     PRAXI      ...           0              0           0       65     0
3     PRAYG      ...           0              0           0       65     0
4     PRAUB      ...           0              0           0       65     0

   FNPT  SyncMob  SyncPC  Seats  Company
0     0        1       0    118     Azul
1     0        1       0    118     Azul
2     0        1       0    118     Azul
3     0        1       0    118     Azul
4     0        1       0    118     Azul

[5 rows x 30 columns]


Dados da tabela 'sqlite_sequence':
         name      seq
0    Aircraft  1000099
1    Airfield  1000751
2  Airfield40        0
3     Country      248
4      Limits  1000004


Dados da tabela 'Airfield':
   AFCode AFIcao                        AFName AFIata  AFCountry  Latitude  \
0       0                                                      0         0
1   21884   SAAR                Islas Malvinas    ROS         10    -32542
2   21896   SACO  Ingeniero Ambrosio Taravella    COR         10    -31194
3   22050   SBAR           Aracaju Santa Maria    AJU         30    -10590
4   22052   SBAT                 Alta Floresta    AFL         30     -9520

   Longitude  AFCat  SyncMob  SyncPC
0          0      0        1       0
1      60471      8        1       0
2      64125      8        1       0
3      37042      8        1       0
4      56063      8        1       1


Dados da tabela 'Airfield40':
    AFCode AFICAO AFIATA            AFName  Latitude  Longitude  AFCountry  \
0 -1000975   WAYP             Potowai Buru     -4170    -134585        101
1 -1000974   WAYL                 Illaga I     -3586    -137373        101
2 -1000973   WABS    NKD             Sinak     -3493    -137504        101
3 -1000972   WABA             Waghete Baru     -4039    -136166        101
4 -1000971   TVSA    SVD  Kingstown Argyle     13096      61089        185

   AFCat  SyncPC  SyncMob
0      6       0        0
1      6       0        0
2      6       0        0
3      8       0        0
4      9       0        0


Dados da tabela 'Country':
   CountryCode     CountryName PrefixICAO ISO3166 RegAC
0            0
1            1     Afghanistan          O      AF  /YA/
2            2         Albania          L      AL  /ZA/
3            3         Algeria          D      DZ  /7T/
4            4  American Samoa          N      AS  /5W/


Dados da tabela 'Delay':
   DelayCode DelayDD                 DelayShort  \
0          6      OA  NO GATE / STAND AVAILABLE
1          9      SG      SCHEDULED GROUND TIME
2         11      PD              LATE CHECK-IN
3         12      PL              LATE CHECK-IN
4         13      PE             CHECK-IN ERROR

                                           DelayLong  DelayGroupCode
0                        Due to own airline activity               1
1  Planned turnaround time less than declared min...               2
2              Check-in reopened for late passengers               3
3      Check-in not completed by flight closure time               3
4            Error with passenger or baggage details               3


Dados da tabela 'DelayGroup':
   DelayGroupCode DelayGG              DelayGroupName
0               1       O                     Parking
1               2       S                      Others
2               3       P       Passenger and Baggage
3               4       C              Cargo and Mail
4               5       G  Aircraft and Ramp Handling


Dados da tabela 'FlightStore':
Empty DataFrame
Columns: [FlightData]
Index: []


Dados da tabela 'Limits':
     LCode  LType  LMinutes  LPeriod                LFrom  \
0  1000001      3       660       14  2018-11-10 14:08:01
1  1000002      1      5100        7  2018-11-10 14:07:55
2  1000003      1     13800       15  2018-11-10 14:07:48
3  1000004      1     51000       12  2018-11-10 14:08:25

                   LTo  LZone  SyncPC
0  2018-11-10 14:08:01      1       0
1  2018-11-10 14:07:55      3       0
2  2018-11-10 14:07:48      4       0
3  2018-11-10 14:08:25      5       0


Dados da tabela 'MobileDelete':
Empty DataFrame
Columns: [TableName, RecordID, ReplaceBy, SyncNr]
Index: []


Dados da tabela 'myQuery':
Empty DataFrame
Columns: [mQCode, ShortName, Name, QuickView, SyncPC]
Index: []


Dados da tabela 'Setting':
   SysCode           Description                      Data  SyncPC   ID
0       36  Reset Import Logbook                                 0  164
1        1      Interface Folder  /Users/Patrick/Downloads       0  165
2       37                E-Mail                                 1  166
3       38           Licence Nbr                                 1  167
4       39         Licence Class                                 1  168


Dados da tabela 'SyncDelete':
Empty DataFrame
Columns: [DeleteSQL]
Index: []


Dados da tabela 'SyncSignature':
Empty DataFrame
Columns: [FlightDate]
Index: []


Dados da tabela 'TypeOfApproach':
   APCode  APCat      APName
0       0      1
1       1      1         ILS
2       2      1         GCA
3       3      1  RNAV (GPS)
4       4      1       JPALS


Dados da tabela 'Validation':
   VCode  VTCode                VDate  VDays VModel VComment  VLanding  \
0     18      28  2020-11-30 00:00:00     10            IFRA         0
1     19       2  2020-07-10 00:00:00     10             CMA         0
2     20       9  2022-01-31 00:00:00    180                         0
3     21       5  2026-01-07 00:00:00    365                         0
4     22      15  2020-11-30 00:00:00     30   E190                  0

   VLandingPeriod  VCCT  VExtra  SyncPC
0               0    12       0       0
1               0    -1       0       0
2               0    -1       0       0
3               0    -1       0       0
4               0    -1       0       0


Dados da tabela 'ValidationTerm':
   VTCode            VTerm
0       1   Flight License
1       2  Medical License
2       3          Landing
3       4         Autoland
4       5         Passport


Dados da tabela 'Weather':
   WxCode              WxRoute  SyncPC
0      -1  Todays Flight Route       0


Dados da tabela 'WeatherAF':
Empty DataFrame
Columns: [WxACode, WxCode, AFCode, SyncPC]
Index: []


Dados da tabela 'Raw_AirlineImport':
Empty DataFrame
Columns: [X, MCC_DATE, FLIGHTNUMBER, AF_DEP, AF_ARR, ROUTE, TIME_DEP, TIME_DEPSCH, TIME_ARR, TIME_ARRSCH, TIME_MODE, TIME_TO, TIME_LDG, TIME_AIR, TIME_TOTAL, TIME_TOTALSIM, TIME_SOLO, TIME_PIC, TIME_PICDAY, TIME_PICNIGHT, TIME_SIC, TIME_SICDAY, TIME_SICNIGHT, TIME_DUAL, TIME_DUALDAY, TIME_DUALNIGHT, TIME_PICUS, TIME_PICUSDAY, TIME_PICUSNIGHT, TIME_INSTRUCTOR, TIME_EXAMINER, TIME_NIGHT, TIME_XC, TIME_IFR, TIME_HOOD, TIME_ACTUAL, TIME_RELIEF, TIME_USER1, TIME_USER2, TIME_USER3, TIME_USER4, CAPACITY, OPERATOR, PILOT1_ID, PILOT1_NAME, PILOT1_PHONE, PILOT1_EMAIL, PILOT2_ID, PILOT2_NAME, PILOT2_PHONE, PILOT2_EMAIL, PILOT3_ID, PILOT3_NAME, PILOT3_PHONE, PILOT3_EMAIL, PILOT4_ID, PILOT4_NAME, PILOT4_PHONE, PILOT4_EMAIL, TO_DAY, TO_NIGHT, LDG_DAY, LDG_NIGHT, LIFT, PF, HOLDING, APP_1, APP_2, APP_3, APP_PRECISION, APP_NONPRECISION, APP_VISUAL, GLIDERLAUNCH, INSTRUCTION, REMARKS, FLIGHTLOG, AUTOLAND, PAIRING, PAX, FUEL, FUELUSED, DELAY, DEICE, USER_NUMERIC, USER_TEXT, USER_YESNO, AC_ISSIM, AC_MAKE, AC_MODEL, AC_VARIANT, AC_REG, AC_FIN, AC_RATING, AC_SP, AC_MP, AC_ME, AC_SPSE, AC_SPME, AC_CLASS, AC_GLIDER, ...]
Index: []

[0 rows x 119 columns]


Dados da tabela 'AircraftCodes':
   ACCode ACRef          Make     Model SubModel  Class  Power
0       1  CONC  Aerospatiale  Concorde               5      6
1       2  AT45  Aerospatiale     ATR42      500      5      6
2       3  AT44  Aerospatiale     ATR42      400      5      6
3       4   SSC  Aerospatiale  Concorde               5      6
4       5  S65C  Aerospatiale    SA365C               4      5


Dados da tabela 'Cloud':
   SyncNr  IsMob   Device            SyncID  Plan  Achv  Cal
0      10      0  MacBook  TFGDPNERGRFH-10Z     0     0    0
1      11      1   iPhone  TFGDPNERGRFH-11A     1     1    0


Dados da tabela 'Allowance':
Empty DataFrame
Columns: [AWCode, AWType, AWModel, AWSubModel, AWDevCode, AWCurrency, AWBase, AWCostVar, AWCostFix, AWOption, AWWord, AWWord2, AWCCT, AWMin, SyncPC]
Index: []


Dados da tabela 'myQueryBuild':
Empty DataFrame
Columns: [mQBCode, mQCode, Build1, Build2, Build3, Build4, SyncPC]
Index: []


Dados da tabela 'AirfieldNotes':
   Id  AFCode                                              Notes  SyncPC
0   1    6673                                       ATIS 128.400       0
1   2    6679                              ATIS 117.00 / 128.000       0
2   4    6750  HF Gander 55-00 \r\n(3485, 6604, 10051, 13270 ...       0
3   6    6814                                       ATIS 128.100       0
4   7    8175                                       ATIS 124.200       0


Dados da tabela 'ExceptionLogs':
Empty DataFrame
Columns: [LogId, LogDate, LogMessage, Stacktrace, InnerException]
Index: []


Dados da tabela 'Pilot':
   PilotCode  Active       PilotName    PilotSearch      PilotPhone  \
0          0       1
1          1       1            Self           SELF  +5551996544293
2    1000001       1           Sales          SALES
3    1000010       1    Carlos Mello    CARLOSMELLO
4    1000013       1  Carlos Jacques  CARLOSJACQUES

     PhoneSearch                     PilotEMail Notes        RosterAlias  \
0
1  5551996544293  patrick_ericksson@hotmail.com        Patrick Ericksson
2
3
4

   Pict PilotRef  SyncMob  SyncPC  SyncPict Company Website
0     0                 1       0         0
1     0   178492        1       0         0    Azul
2     0   116136        1       0         0    Azul    None
3     0   554410        1       0         0    Azul    None
4     0   120890        1       0         0    Azul    None


Dados da tabela 'Flight':
   FlightCode  FlightDate  AircraftCode  DepCode  ArrCode FlightNumber  \
0     1000001  2018-04-05       1000053   -22083   -22098       AD5230
1     1000002  2018-04-05       1000053   -22098   -22171       AD5230
2     1000003  2018-04-07       1000045   -22171   -22070       AD5305
3     1000004  2018-04-08       1000049   -22070   -22171       AD5302
4     1000005  2018-04-09       1000039   -22171   -22070       AD4423

   DepTime  DepTimeSCH  DepOffset  ArrTime  ...  CurrPilot  CostPerDiem  \
0      895         895       -240      986  ...          9            0
1     1021        1005       -180     1143  ...          9            0
2     1262        1275       -180     1360  ...          9            0
3       20          15       -180      114  ...          9            0
4     1107        1110       -180     1213  ...          9            0

   CurrPerDiem  TimeTO  TimeLDG  minAIR  SyncMob  SyncPC  RecStatus  \
0            9     916      983      67        1       0          0
1            9    1034     1139     105        1       0          0
2            9    1270     1357      87        1       0          0
3            9      35      110      75        1       0          0
4            9    1122     1209      87        1       0          0

   BaseOffset
0        -180
1        -180
2        -180
3        -180
4        -180

[5 rows x 73 columns]

In [6]:
# Fechar a conexão com o banco de dados
conn.close()

In [7]:
for table, df in dataframes.items():
    print(f"Tabela: {table}")
    print(df.head())

Tabela: Aircraft
   AircraftCode  Active  DeviceCode     Make Model SubModel Rating Reference  \
0       1000006       1           1  Embraer  E190            E179    PR-AXE
1       1000007       1           1  Embraer  E190            E179    PR-AUJ
2       1000008       1           1  Embraer  E190            E179    PR-AXI
3       1000009       1           1  Embraer  E190            E179    PR-AYG
4       1000010       1           1  Embraer  E190            E179    PR-AUB

  RefSearch Fin  ...  DefaultApp  DefaultLaunch  DefaultLog  CondLog  Run2  \
0     PRAXE      ...           0              0           0       65     0
1     PRAUJ      ...           0              0           0       65     0
2     PRAXI      ...           0              0           0       65     0
3     PRAYG      ...           0              0           0       65     0
4     PRAUB      ...           0              0           0       65     0

   FNPT  SyncMob  SyncPC  Seats  Company
0     0        1       0    118     Azul
1     0        1       0    118     Azul
2     0        1       0    118     Azul
3     0        1       0    118     Azul
4     0        1       0    118     Azul

[5 rows x 30 columns]
Tabela: sqlite_sequence
         name      seq
0    Aircraft  1000099
1    Airfield  1000751
2  Airfield40        0
3     Country      248
4      Limits  1000004
Tabela: Airfield
   AFCode AFIcao                        AFName AFIata  AFCountry  Latitude  \
0       0                                                      0         0
1   21884   SAAR                Islas Malvinas    ROS         10    -32542
2   21896   SACO  Ingeniero Ambrosio Taravella    COR         10    -31194
3   22050   SBAR           Aracaju Santa Maria    AJU         30    -10590
4   22052   SBAT                 Alta Floresta    AFL         30     -9520

   Longitude  AFCat  SyncMob  SyncPC
0          0      0        1       0
1      60471      8        1       0
2      64125      8        1       0
3      37042      8        1       0
4      56063      8        1       1
Tabela: Airfield40
    AFCode AFICAO AFIATA            AFName  Latitude  Longitude  AFCountry  \
0 -1000975   WAYP             Potowai Buru     -4170    -134585        101
1 -1000974   WAYL                 Illaga I     -3586    -137373        101
2 -1000973   WABS    NKD             Sinak     -3493    -137504        101
3 -1000972   WABA             Waghete Baru     -4039    -136166        101
4 -1000971   TVSA    SVD  Kingstown Argyle     13096      61089        185

   AFCat  SyncPC  SyncMob
0      6       0        0
1      6       0        0
2      6       0        0
3      8       0        0
4      9       0        0
Tabela: Country
   CountryCode     CountryName PrefixICAO ISO3166 RegAC
0            0
1            1     Afghanistan          O      AF  /YA/
2            2         Albania          L      AL  /ZA/
3            3         Algeria          D      DZ  /7T/
4            4  American Samoa          N      AS  /5W/
Tabela: Delay
   DelayCode DelayDD                 DelayShort  \
0          6      OA  NO GATE / STAND AVAILABLE
1          9      SG      SCHEDULED GROUND TIME
2         11      PD              LATE CHECK-IN
3         12      PL              LATE CHECK-IN
4         13      PE             CHECK-IN ERROR

                                           DelayLong  DelayGroupCode
0                        Due to own airline activity               1
1  Planned turnaround time less than declared min...               2
2              Check-in reopened for late passengers               3
3      Check-in not completed by flight closure time               3
4            Error with passenger or baggage details               3
Tabela: DelayGroup
   DelayGroupCode DelayGG              DelayGroupName
0               1       O                     Parking
1               2       S                      Others
2               3       P       Passenger and Baggage
3               4       C              Cargo and Mail
4               5       G  Aircraft and Ramp Handling
Tabela: FlightStore
Empty DataFrame
Columns: [FlightData]
Index: []
Tabela: Limits
     LCode  LType  LMinutes  LPeriod                LFrom  \
0  1000001      3       660       14  2018-11-10 14:08:01
1  1000002      1      5100        7  2018-11-10 14:07:55
2  1000003      1     13800       15  2018-11-10 14:07:48
3  1000004      1     51000       12  2018-11-10 14:08:25

                   LTo  LZone  SyncPC
0  2018-11-10 14:08:01      1       0
1  2018-11-10 14:07:55      3       0
2  2018-11-10 14:07:48      4       0
3  2018-11-10 14:08:25      5       0
Tabela: MobileDelete
Empty DataFrame
Columns: [TableName, RecordID, ReplaceBy, SyncNr]
Index: []
Tabela: myQuery
Empty DataFrame
Columns: [mQCode, ShortName, Name, QuickView, SyncPC]
Index: []
Tabela: Setting
   SysCode           Description                      Data  SyncPC   ID
0       36  Reset Import Logbook                                 0  164
1        1      Interface Folder  /Users/Patrick/Downloads       0  165
2       37                E-Mail                                 1  166
3       38           Licence Nbr                                 1  167
4       39         Licence Class                                 1  168
Tabela: SyncDelete
Empty DataFrame
Columns: [DeleteSQL]
Index: []
Tabela: SyncSignature
Empty DataFrame
Columns: [FlightDate]
Index: []
Tabela: TypeOfApproach
   APCode  APCat      APName
0       0      1
1       1      1         ILS
2       2      1         GCA
3       3      1  RNAV (GPS)
4       4      1       JPALS
Tabela: Validation
   VCode  VTCode                VDate  VDays VModel VComment  VLanding  \
0     18      28  2020-11-30 00:00:00     10            IFRA         0
1     19       2  2020-07-10 00:00:00     10             CMA         0
2     20       9  2022-01-31 00:00:00    180                         0
3     21       5  2026-01-07 00:00:00    365                         0
4     22      15  2020-11-30 00:00:00     30   E190                  0

   VLandingPeriod  VCCT  VExtra  SyncPC
0               0    12       0       0
1               0    -1       0       0
2               0    -1       0       0
3               0    -1       0       0
4               0    -1       0       0
Tabela: ValidationTerm
   VTCode            VTerm
0       1   Flight License
1       2  Medical License
2       3          Landing
3       4         Autoland
4       5         Passport
Tabela: Weather
   WxCode              WxRoute  SyncPC
0      -1  Todays Flight Route       0
Tabela: WeatherAF
Empty DataFrame
Columns: [WxACode, WxCode, AFCode, SyncPC]
Index: []
Tabela: Raw_AirlineImport
Empty DataFrame
Columns: [X, MCC_DATE, FLIGHTNUMBER, AF_DEP, AF_ARR, ROUTE, TIME_DEP, TIME_DEPSCH, TIME_ARR, TIME_ARRSCH, TIME_MODE, TIME_TO, TIME_LDG, TIME_AIR, TIME_TOTAL, TIME_TOTALSIM, TIME_SOLO, TIME_PIC, TIME_PICDAY, TIME_PICNIGHT, TIME_SIC, TIME_SICDAY, TIME_SICNIGHT, TIME_DUAL, TIME_DUALDAY, TIME_DUALNIGHT, TIME_PICUS, TIME_PICUSDAY, TIME_PICUSNIGHT, TIME_INSTRUCTOR, TIME_EXAMINER, TIME_NIGHT, TIME_XC, TIME_IFR, TIME_HOOD, TIME_ACTUAL, TIME_RELIEF, TIME_USER1, TIME_USER2, TIME_USER3, TIME_USER4, CAPACITY, OPERATOR, PILOT1_ID, PILOT1_NAME, PILOT1_PHONE, PILOT1_EMAIL, PILOT2_ID, PILOT2_NAME, PILOT2_PHONE, PILOT2_EMAIL, PILOT3_ID, PILOT3_NAME, PILOT3_PHONE, PILOT3_EMAIL, PILOT4_ID, PILOT4_NAME, PILOT4_PHONE, PILOT4_EMAIL, TO_DAY, TO_NIGHT, LDG_DAY, LDG_NIGHT, LIFT, PF, HOLDING, APP_1, APP_2, APP_3, APP_PRECISION, APP_NONPRECISION, APP_VISUAL, GLIDERLAUNCH, INSTRUCTION, REMARKS, FLIGHTLOG, AUTOLAND, PAIRING, PAX, FUEL, FUELUSED, DELAY, DEICE, USER_NUMERIC, USER_TEXT, USER_YESNO, AC_ISSIM, AC_MAKE, AC_MODEL, AC_VARIANT, AC_REG, AC_FIN, AC_RATING, AC_SP, AC_MP, AC_ME, AC_SPSE, AC_SPME, AC_CLASS, AC_GLIDER, ...]
Index: []

[0 rows x 119 columns]
Tabela: AircraftCodes
   ACCode ACRef          Make     Model SubModel  Class  Power
0       1  CONC  Aerospatiale  Concorde               5      6
1       2  AT45  Aerospatiale     ATR42      500      5      6
2       3  AT44  Aerospatiale     ATR42      400      5      6
3       4   SSC  Aerospatiale  Concorde               5      6
4       5  S65C  Aerospatiale    SA365C               4      5
Tabela: Cloud
   SyncNr  IsMob   Device            SyncID  Plan  Achv  Cal
0      10      0  MacBook  TFGDPNERGRFH-10Z     0     0    0
1      11      1   iPhone  TFGDPNERGRFH-11A     1     1    0
Tabela: Allowance
Empty DataFrame
Columns: [AWCode, AWType, AWModel, AWSubModel, AWDevCode, AWCurrency, AWBase, AWCostVar, AWCostFix, AWOption, AWWord, AWWord2, AWCCT, AWMin, SyncPC]
Index: []
Tabela: myQueryBuild
Empty DataFrame
Columns: [mQBCode, mQCode, Build1, Build2, Build3, Build4, SyncPC]
Index: []
Tabela: AirfieldNotes
   Id  AFCode                                              Notes  SyncPC
0   1    6673                                       ATIS 128.400       0
1   2    6679                              ATIS 117.00 / 128.000       0
2   4    6750  HF Gander 55-00 \r\n(3485, 6604, 10051, 13270 ...       0
3   6    6814                                       ATIS 128.100       0
4   7    8175                                       ATIS 124.200       0
Tabela: ExceptionLogs
Empty DataFrame
Columns: [LogId, LogDate, LogMessage, Stacktrace, InnerException]
Index: []
Tabela: Pilot
   PilotCode  Active       PilotName    PilotSearch      PilotPhone  \
0          0       1
1          1       1            Self           SELF  +5551996544293
2    1000001       1           Sales          SALES
3    1000010       1    Carlos Mello    CARLOSMELLO
4    1000013       1  Carlos Jacques  CARLOSJACQUES

     PhoneSearch                     PilotEMail Notes        RosterAlias  \
0
1  5551996544293  patrick_ericksson@hotmail.com        Patrick Ericksson
2
3
4

   Pict PilotRef  SyncMob  SyncPC  SyncPict Company Website
0     0                 1       0         0
1     0   178492        1       0         0    Azul
2     0   116136        1       0         0    Azul    None
3     0   554410        1       0         0    Azul    None
4     0   120890        1       0         0    Azul    None
Tabela: Flight
   FlightCode  FlightDate  AircraftCode  DepCode  ArrCode FlightNumber  \
0     1000001  2018-04-05       1000053   -22083   -22098       AD5230
1     1000002  2018-04-05       1000053   -22098   -22171       AD5230
2     1000003  2018-04-07       1000045   -22171   -22070       AD5305
3     1000004  2018-04-08       1000049   -22070   -22171       AD5302
4     1000005  2018-04-09       1000039   -22171   -22070       AD4423

   DepTime  DepTimeSCH  DepOffset  ArrTime  ...  CurrPilot  CostPerDiem  \
0      895         895       -240      986  ...          9            0
1     1021        1005       -180     1143  ...          9            0
2     1262        1275       -180     1360  ...          9            0
3       20          15       -180      114  ...          9            0
4     1107        1110       -180     1213  ...          9            0

   CurrPerDiem  TimeTO  TimeLDG  minAIR  SyncMob  SyncPC  RecStatus  \
0            9     916      983      67        1       0          0
1            9    1034     1139     105        1       0          0
2            9    1270     1357      87        1       0          0
3            9      35      110      75        1       0          0
4            9    1122     1209      87        1       0          0

   BaseOffset
0        -180
1        -180
2        -180
3        -180
4        -180

[5 rows x 73 columns]

In [9]:
df_combined = pd.concat(dataframes.values(), ignore_index=True)
print(df_combined.head())

   AircraftCode  Active  DeviceCode     Make Model SubModel Rating Reference  \
0     1000006.0     1.0         1.0  Embraer  E190            E179    PR-AXE
1     1000007.0     1.0         1.0  Embraer  E190            E179    PR-AUJ
2     1000008.0     1.0         1.0  Embraer  E190            E179    PR-AXI
3     1000009.0     1.0         1.0  Embraer  E190            E179    PR-AYG
4     1000010.0     1.0         1.0  Embraer  E190            E179    PR-AUB

  RefSearch Fin  ...  CurrRent  CostPilot  CurrPilot  CostPerDiem  \
0     PRAXE      ...       NaN        NaN        NaN          NaN
1     PRAUJ      ...       NaN        NaN        NaN          NaN
2     PRAXI      ...       NaN        NaN        NaN          NaN
3     PRAYG      ...       NaN        NaN        NaN          NaN
4     PRAUB      ...       NaN        NaN        NaN          NaN

   CurrPerDiem  TimeTO  TimeLDG  minAIR  RecStatus  BaseOffset
0          NaN     NaN      NaN     NaN        NaN         NaN
1          NaN     NaN      NaN     NaN        NaN         NaN
2          NaN     NaN      NaN     NaN        NaN         NaN
3          NaN     NaN      NaN     NaN        NaN         NaN
4          NaN     NaN      NaN     NaN        NaN         NaN

[5 rows x 324 columns]

/var/folders/nn/889q9xtn0_j3k8ncb63kj20w0000gn/T/ipykernel_1521/596833511.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_combined = pd.concat(dataframes.values(), ignore_index=True)